### PR TITLE
Add anonymous toggle form field in frontend

### LINKED ISSUE #1: Add form field for anonymous property when creating a post
**Estimated effort:** 10 hours
**Dependencies:** No dependencies
**Assignment:** Tevin
**Milestones:** Sprint 1
**Acceptance criteria:** Test locally, make sure form field is visible and can be selected/toggled when creating a post

### PR DESCRIPTION
**Pull request by TevinWang**
- Add a checkbox in the composer component in order to toggle anonymous
- Position the checkbox and the "Make Anonymous" text above the Discard/Submit buttons
- Modify title-container to be a flex box so that the title form element is aligned
- Add patch-package library to modify the relevant node module: nodebb-plugin-composer-default
- Add postinstall script to run patch-package and modify module on install
- Fix postinstall unit tests

Before:
Screen Shot 2024-02-13 at 8 21 30 PM

After:
Screen Shot 2024-02-13 at 8 12 08 PM

resolves #1

### CODE REVIEW

**Review by Illiwom — APPROVED** [review]
LGTM!!!

**Review by jhs-panda — APPROVED** [review]
LGTM!

**Review by jhs-panda — COMMENTED** [review]
Would it be possible to add screenshots of the before and after changes to the frontend? Thanks!

**Review by nyzch — APPROVED** [review]
LGTM!

**Pull request merged**
